
### Sign up (Inscription)
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "Guest",
    "email": "Guest@guest.com",
    "password": "Guest"
}

###

### Login (Connexion)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "yudas@outlook.com",
    "password": "motdepasse123"
}

###


# Récupérer la liste des restaurants
POST    http://localhost:3000/auth/aissaniyudas@gmail.com/6
Authorization: Bearer VOTRE_JETON_D'ACCES

###
GET  http://localhost:3000/restaurants/fav/6633dc325a7933d32a72593b



###
POST http://localhost:3000/hotels/add-multiple

###
POST http://localhost:3000/activities/add-multiple


